/**
 * Speaker chip colors, shared between the diarization pipeline (main) and the
 * chip color picker (renderer).
 *
 * Drawn from the brand palette first, then hues far enough apart to stay
 * distinct once a recording runs past four people, and to remain
 * distinguishable for the most common forms of colour blindness. Each is used
 * as a hue to mix from rather than painted directly, so they hold up on white
 * and on navy.
 */
export const SPEAKER_COLORS = [
  '#4f7cff',
  '#32a071',
  '#e5a43b',
  '#d94c4c',
  '#7a5af8',
  '#0ba5a5',
  '#db4f9e',
  '#667085'
]

/**
 * Picks a color none of `usedColors` already has.
 *
 * The curated palette above runs out at eight distinct, colourblind-safe
 * hues; past that, a color is generated by stepping around the hue wheel by
 * the golden angle, which keeps consecutive generated hues visually far apart
 * instead of clustering. It won't be colourblind-tuned like the curated set,
 * but two speakers sharing a color is a worse outcome than one — this is the
 * fallback once a recording runs past what a hand-picked palette can cover.
 */
export function pickSpeakerColor(usedColors: readonly string[]): string {
  const used = new Set(usedColors)

  const free = SPEAKER_COLORS.find((c) => !used.has(c))
  if (free) return free

  const GOLDEN_ANGLE = 137.508
  // Bounded rather than infinite: correct behavior past a few hundred
  // simultaneous speakers is not worth chasing, and a hang is worse than a
  // rare, harmless repeat.
  for (let i = 0; i < 1000; i++) {
    const color = `hsl(${Math.round((i * GOLDEN_ANGLE) % 360)}, 65%, 55%)`
    if (!used.has(color)) return color
  }
  return SPEAKER_COLORS[0]
}
